In [1]:
!python --version

Python 3.11.9


In [3]:
import pandas as pd

### Question 1

In [4]:
pd.__version__

'2.2.2'

In [7]:
!pip install wget

  Using cached wget-3.2-py3-none-any.whl


In [8]:
import wget

In [10]:
url = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv'
wget.download(url, 'laptops.csv')

100% [............................................................................] 298573 / 298573

'laptops.csv'

In [13]:
df_laptops = pd.read_csv("laptops.csv")

### Question 2

In [69]:
len(df_laptops)

2160

### Question 3

In [47]:
df_laptops.Brand.unique()

array(['Asus', 'Alurin', 'MSI', 'HP', 'Lenovo', 'Medion', 'Acer', 'Apple',
       'Razer', 'Gigabyte', 'Dell', 'LG', 'Samsung', 'PcCom', 'Microsoft',
       'Primux', 'Prixton', 'Dynabook Toshiba', 'Thomson', 'Denver',
       'Deep Gaming', 'Vant', 'Innjoo', 'Jetwing', 'Millenium', 'Realme',
       'Toshiba'], dtype=object)

In [27]:
df_laptops.Brand.nunique()

27

### Question 4

In [28]:
df_laptops.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

### Question 5

In [30]:
df_laptops.groupby("Brand")["Final Price"].max()["Dell"]

3936.0

### Question 6

In [33]:
df_laptops["Screen"].describe()

count    2156.000000
mean       15.168112
std         1.203329
min        10.100000
25%        14.000000
50%        15.600000
75%        15.600000
max        18.000000
Name: Screen, dtype: float64

In [40]:
mode = df_laptops["Screen"].mode()

In [42]:
mode[0]

15.6

In [43]:
df_fillna = df_laptops.fillna(mode[0])

In [46]:
df_fillna.isnull().sum()

Laptop          0
Status          0
Brand           0
Model           0
CPU             0
RAM             0
Storage         0
Storage type    0
GPU             0
Screen          0
Touch           0
Final Price     0
dtype: int64

In [44]:
df_fillna["Screen"].describe()

count    2160.000000
mean       15.168912
std         1.202357
min        10.100000
25%        14.000000
50%        15.600000
75%        15.600000
max        18.000000
Name: Screen, dtype: float64

### Question 7

In [49]:
df_innjoo = df_laptops[df_laptops.Brand == "Innjoo"]

In [51]:
len(df_innjoo)

6

In [56]:
df_sub = df_innjoo[["RAM", "Storage", "Screen"]]

In [53]:
import numpy as np

In [59]:
X = np.array(df_sub)

In [60]:
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [65]:
X2 = X.T.dot(X)

In [62]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [63]:
y

array([1100, 1300,  800,  900, 1000, 1100])

In [66]:
res = np.linalg.inv(X2).dot(X.T).dot(y)

In [67]:
res

array([45.58076606,  0.42783519, 45.29127938])

In [68]:
res.sum()

91.29988062995815